-- docs/operations/finance-mvp-rollback.sql
-- Guarded rollback script for HurCELL Finance MVP.
-- Target: Drops Finance schema objects introduced in 20260716130000_finance_installments_mvp.sql
-- Safety: Dynamic PL/pgSQL block with transactional empty-schema validation and ACCESS EXCLUSIVE locking.

--------------------------------------------------------------------------------
-- SECTION A: READ-ONLY ROLLBACK ELIGIBILITY CHECKS
--------------------------------------------------------------------------------
-- This SELECT returns the current state of Finance objects and eligibility.
-- All counts must be 0 and present = true for safe rollback.
SELECT
  to_regclass('public.finance_plans') IS NOT NULL AS plans_table_present,
  to_regclass('public.finance_installments') IS NOT NULL AS installments_table_present,
  to_regclass('public.finance_collections') IS NOT NULL AS collections_table_present,
  to_regclass('public.finance_audit_logs') IS NOT NULL AS audit_logs_table_present,
  coalesce((SELECT count(*) FROM public.finance_plans), 0) AS plans_row_count,
  coalesce((SELECT count(*) FROM public.finance_installments), 0) AS installments_row_count,
  coalesce((SELECT count(*) FROM public.finance_collections), 0) AS collections_row_count,
  coalesce((SELECT count(*) FROM public.finance_audit_logs), 0) AS audit_logs_row_count,
  (
    coalesce((SELECT count(*) FROM public.finance_plans), 0) = 0 AND
    coalesce((SELECT count(*) FROM public.finance_installments), 0) = 0 AND
    coalesce((SELECT count(*) FROM public.finance_collections), 0) = 0 AND
    coalesce((SELECT count(*) FROM public.finance_audit_logs), 0) = 0
  ) AS empty_schema_eligibility;


--------------------------------------------------------------------------------
-- SECTION B: ATOMIC GUARDED DESTRUCTIVE BLOCK (No top-level DROP/ALTER statement)
--------------------------------------------------------------------------------
-- DO NOT edit this file directly in production to activate.
-- Prepare an active copy with v_execute_rollback := true, verify its SHA256,
-- and obtain independent approval before execution.
DO $$
DECLARE
  v_execute_rollback CONSTANT boolean := false; -- Keep false unless executing approved copy

  v_plans_count INT := 0;
  v_installments_count INT := 0;
  v_collections_count INT := 0;
  v_audit_logs_count INT := 0;
BEGIN
  -- 1. Manual approval boundary check
  IF NOT v_execute_rollback THEN
    RAISE EXCEPTION 'Manual approval required: v_execute_rollback is false. Re-run aborted.';
  END IF;

  -- 2. Transactional ACCESS EXCLUSIVE locking to prevent concurrent writes
  IF to_regclass('public.finance_plans') IS NOT NULL THEN
    LOCK TABLE public.finance_plans IN ACCESS EXCLUSIVE MODE;
  END IF;
  IF to_regclass('public.finance_installments') IS NOT NULL THEN
    LOCK TABLE public.finance_installments IN ACCESS EXCLUSIVE MODE;
  END IF;
  IF to_regclass('public.finance_collections') IS NOT NULL THEN
    LOCK TABLE public.finance_collections IN ACCESS EXCLUSIVE MODE;
  END IF;
  IF to_regclass('public.finance_audit_logs') IS NOT NULL THEN
    LOCK TABLE public.finance_audit_logs IN ACCESS EXCLUSIVE MODE;
  END IF;

  -- 3. Re-calculate row counts after securing access exclusive locks
  IF to_regclass('public.finance_plans') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.finance_plans' INTO v_plans_count;
  END IF;
  IF to_regclass('public.finance_installments') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.finance_installments' INTO v_installments_count;
  END IF;
  IF to_regclass('public.finance_collections') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.finance_collections' INTO v_collections_count;
  END IF;
  IF to_regclass('public.finance_audit_logs') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.finance_audit_logs' INTO v_audit_logs_count;
  END IF;

  -- 4. Empty-schema gate check
  IF v_plans_count > 0 OR v_installments_count > 0 OR v_collections_count > 0 OR v_audit_logs_count > 0 THEN
    RAISE EXCEPTION 'Rollback aborted: One or more locked Finance tables contain records (plans: %, installments: %, collections: %, audit_logs: %). Safe empty-schema constraint failed.',
      v_plans_count, v_installments_count, v_collections_count, v_audit_logs_count;
  END IF;

  -- 5. Execution of drops inside the transaction block (No CASCADE, exact signatures)
  EXECUTE 'DROP TRIGGER IF EXISTS prevent_collections_modifications ON public.finance_collections';
  EXECUTE 'DROP TRIGGER IF EXISTS prevent_audit_logs_modifications ON public.finance_audit_logs';

  EXECUTE 'DROP FUNCTION IF EXISTS public.create_finance_plan(text,uuid,text,text,numeric,numeric,numeric,smallint,smallint,date,text,text)';
  EXECUTE 'DROP FUNCTION IF EXISTS public.record_finance_collection(text,uuid,numeric,text,text,timestamptz,text,text)';
  EXECUTE 'DROP FUNCTION IF EXISTS public.cancel_finance_plan(uuid,text,text)';
  EXECUTE 'DROP FUNCTION IF EXISTS public.prevent_finance_append_only_update_delete()';

  EXECUTE 'DROP TABLE IF EXISTS public.finance_audit_logs';
  EXECUTE 'DROP TABLE IF EXISTS public.finance_collections';
  EXECUTE 'DROP TABLE IF EXISTS public.finance_installments';
  EXECUTE 'DROP TABLE IF EXISTS public.finance_plans';

  EXECUTE 'DROP SEQUENCE IF EXISTS public.finance_receipt_seq';

  RAISE NOTICE 'Finance empty-schema rollback executed successfully.';
END;
$$;


--------------------------------------------------------------------------------
-- SECTION C: LEDGER COMPATIBILITY ROLLBACK CONSIDERATIONS
--------------------------------------------------------------------------------
/*
Ledger readiness migration changes (20260716120000_credit_ledger_finance_readiness.sql) 
should be reviewed manually before rollback. 

1. NUMERIC(12,2) Type Widening:
   - Changing amount and balance_after to numeric(12,2) is a backward-compatible 
     precision enhancement. It is strongly recommended to PRESERVE this widening 
     rather than attempting to shrink/revert types, to avoid truncation errors.

2. uniq_credit_accounts_credit_customer_id Index:
   - This unique constraint enforces single-account integrity. It is a general 
     safety enhancement and should be PRESERVED.

3. source_type Constraint Reversion:
   - Restoring the old source_type check constraint (excluding 'service_order' and 'manual')
     is ONLY possible if no records with these values exist in the database:
     
     SELECT count(*) 
     FROM public.credit_transactions 
     WHERE source_type IN ('service_order', 'manual');
     
   - If the count is 0, the constraint can be reverted by running:
     ALTER TABLE public.credit_transactions 
       DROP CONSTRAINT IF EXISTS chk_credit_transactions_source_type;
     ALTER TABLE public.credit_transactions 
       ADD CONSTRAINT chk_credit_transactions_source_type 
       CHECK (source_type = ANY (ARRAY['web_order'::text, 'store_sale'::text, 'service_fee'::text, 'print_fee'::text, 'technical_service_fee'::text, 'payment'::text, 'adjustment'::text, 'reversal'::text]));

4. add_credit_transaction RPC Reversion:
   - Reverting the RPC public.add_credit_transaction requires reverting the function 
     body from the new V11/V12/V13/V14 body fingerprint ('31b929d45764fd5c6d6144bdddb2b328') 
     to the legacy production fingerprint ('b7620bc75905ac461f37ab32fc0b430e').
   - Legacy RPC reversion SQL is NOT active in this file. It requires a separate, 
     fully audited migration.
*/


--------------------------------------------------------------------------------
-- SECTION D: MANUAL APPROVAL BOUNDARY
--------------------------------------------------------------------------------
-- The execution of any part of this rollback script requires explicit written 
-- approval from the DB administrator and system owner.
--
-- APPROVED BY: ______________________  DATE: __________________
